### ISSUE TITLE
Modules - Timed update fires before activation requirements are first checked

### ISSUE THREAD

**Issue by SpoinkyNL** [Artemis-RGB/Artemis#481]
@diogotr7 on Discord

> I also noticed a timed update being called right when the plug-in is loaded
> Happens with my league module
> I only noticed because it throws http exceptions when loading the plug-in when the calls to the game http server obviously fail
> (without the activation requirements being met)

**Comment by diogotr7** [comment]
I investigated this a little bit and found that the plugin is updated before it is enabled. This means the activation check is always true, since the activation requirements list is empty before enabling.

**Comment by SpoinkyNL** [comment]
We've pushed a fix for this, lets close this issue if it doesn't arise again in the next few days
