### ISSUE TITLE
Editor - Add generic events for property changes

### ISSUE THREAD

**Issue by diogotr7** [Artemis-RGB/Artemis#495]
These events would allow the user to trigger an animation when for example, they score a goal in a game (trigger when number of goals increases). It would also allow for this to be independent from the plugin, meaning a plugin doesn't need to add several events for each property.

Rough idea of how a UI for this might look:

![image](https://cdn.discordapp.com/attachments/392093058352676876/770739821526122556/unknown.png)

Events I would find useful:
* On Change
* On Increase
* On Decrease

**Comment by SpoinkyNL** [comment]
I guess this would be a third option when clicking the plus sign?

**Comment by diogotr7** [comment]
I'm not sure how you've added events, but yes imo. This should be a third option.

**Comment by SpoinkyNL** [comment]
Events just turn into a yellow event node when you select an event in the data model.
 I like the idea of it being a third option though as this is not really something we can determine by what you select in the data model

**Comment by SpoinkyNL** [comment]
This has been implemented. When choosing 'add event condition' you can now pick any regular property and it'll turn into a 'changed' event:
![image](https://user-images.githubusercontent.com/8858506/111903367-42e96a00-8a42-11eb-8085-4b34be6ee5bc.png)
