### ISSUE TITLE
Editor - Copy and paste layers and folders

### ISSUE THREAD

**Issue by diogotr7** [Artemis-RGB/Artemis#498]
Would be useful for making several similar layers with slight differences. Should be doable with ctrl + c / v and through the right click menu.

**Comment by SpoinkyNL** [comment]
We have a really basic duplicate now but before release I want to expand this into proper copy/paste functionality

https://github.com/Artemis-RGB/Artemis/projects/12#card-48961887

**Comment by SpoinkyNL** [comment]
Implemented in https://github.com/Artemis-RGB/Artemis/commit/010d7a3e40584291c1b7b41bd4655d72b184134c
