### ISSUE TITLE
VirusTotal detection 1/69

### ISSUE THREAD

**Issue by Eyji** [Artemis-RGB/Artemis#514]
https://www.virustotal.com/gui/file/1782097685f1a983b01a56b0154a76c297141f1e92bd1d1fc1c3b263f0b27192/detection

**Comment by SpoinkyNL** [comment]
Hello, thanks for the report.
This is a false positive purely triggered by the fact that one of the DLLs is not signed.

![image](https://user-images.githubusercontent.com/8858506/101521140-afee5d80-3985-11eb-8e45-7f9a17bcddbc.png)

Unfortunately there's nothing we can do about this without purchasing an expensive code certificate, but you can safely ignore this detection :)
