### ISSUE TITLE
Plugin API - Allow for custom DataModelDescription in AddDynamicChild

### ISSUE THREAD

**Issue by diogotr7** [Artemis-RGB/Artemis#518]
Currently AddDynamicChild has this signature:

```cs
public T AddDynamicChild<T>(T dynamicDataModel, string key, string? name = null, string? description = null) where T : DataModel
```

which allows plugin developers to set a custom name and description if needed. In my use case, I want to be able to add a custom affix per DataModel (Sensor units on my HwInfo64, V, Mhz, etc).

This could be implemented as additional arguments for each property in the method above, or by replacing the `name` and `description` arguments by a `DataModelPropertyAttribute`:
```cs
public T AddDynamicChild<T>(T dynamicDataModel, string key, DataModelPropertyAttribute? description= null) where T : DataModel
```

The current humanizing the key behaviour could be kept if this description is left null.

**Comment by SpoinkyNL** [comment]
I think I'd passing the attribute to that method is the best approach.

However, I'd like this as an extra overload so that if you just want a custom name you don't immediately have to provide a full blown `DataModelPropertyAttribute`.
