### ISSUE TITLE
Application is useless for common users

### ISSUE THREAD

**Issue by H0lySh1t** [Artemis-RGB/Artemis#527]
Well done you made everything that is respectable from a programmers viewpoint, however the software became useless. I took like 20 mins to figure out how to create a rainbow effect on my rgb keyboard yet i'm stuck. I figured 2 things: I'm too stupid for this and this is way too complicated. If you intend to keep it this way at least include some presets, otherwise this is worse than v1.
I'm really sorry because I know what it means to put endless hours into a project that is awesome but only for those who involved in the development.
Please make this user-friendly with a buttton like "basic" or something.

**Comment by gitmacer** [comment]
if you mainly want to control mice and keyboard. Feelfree to take a look at [aurora](https://github.com/antonpup/Aurora) it is way easier to understand.

**Comment by SpoinkyNL** [comment]
Thank you for your feedback. The approach I decided upon with Artemis 2 was to first cater to the most advanced usages, they were the most challenging to solve with how Artemis 1 was set up.

From there I try to make simple things simple to achieve.

To quote the [getting started guide](https://wiki.artemis-rgb.com/en/guides/user#before-you-start)

> You should realise that some parts of Artemis are not intended to be simple to understand straight away. While we try to make Artemis as easy to *use* as possible, it may not be very easy to fully *learn*.  
> 
> If you've ever worked with video editing software (and especially [Adobe After Effects](https://www.adobe.com/nl/products/aftereffects.html)) you will quickly find some similarities and the interface should come across as fairly familliar.
> 
> If you've never used any kind of video editing software: **Don't worry!** Artemis isn't as intimidating as something like an Adobe product and when you follow these guides you'll be fine :).

Setting up a rainbow effect shouldn't be a big struggle once you know the UI though, here's how I did it

https://user-images.githubusercontent.com/8858506/104785715-792d1380-578b-11eb-8238-6b0ceec9d58e.mp4
