### ISSUE TITLE
Linux support 

### ISSUE THREAD

**Issue by NicTanghe** [Artemis-RGB/Artemis#535]
Hello so i realize the proj is to far in development to switch from a windows run language to something usefull.

But i`m still going to try to convince people to make a Linux port because windows is terrible at managing resources and the only thing that makes them not suck is NVIDIA not having popper Linux drivers.

So is there anny chanse that this will be supported on linux ?

**Comment by SpoinkyNL** [comment]
Hi, thanks for your interest

As per our [FAQ](https://wiki.artemis-rgb.com/en/faq):

> Q: Will Artemis be cross platform?
> A: Maybe. The core is written in .NET Core and can be compiled for Linux with minimal changes.
> The UI is a different story, it is written in WPF which is a Windows-only platform. Artemis can function without the UI though and a different UI based on cross-platform frameworks can be put in place as well. I don't currently have any plans to do this but perhaps when Artemis 2 has matured enough and is feature complete, it would be a nice endeavour.
> 
> There is also the option of running Artemis in Wine, with which some users on Discord had succes in combination with the OpenRGB plugin.

**Comment by NicTanghe** [comment]
Hello it seems the artemis Linux port is done.

i`m a bit lost on how to build it though...

**Comment by NicTanghe** [comment]
ah you just need to allow it to run as a program.
