### ISSUE TITLE
rotated fan displays incorrectly in surface vs. overlay editors

### ISSUE THREAD

**Issue by pryankster** [Artemis-RGB/Artemis#536]
My rear fan is rotated 90 degrees clockwise.  In the surface editor, I changed the rotation property to 90 degrees.
![image](https://user-images.githubusercontent.com/4298409/106521629-5e4ce580-6493-11eb-8fef-0f1667760d12.png)

In the layout editor, when I click on the top/outer LED of the fan (Corsair LL120), the right/outer LED lights up on the fan, as well as on the layout editor, but the layout editor shows the top LED as selected:

![image](https://user-images.githubusercontent.com/4298409/106521473-25ad0c00-6493-11eb-8b98-85a1f109db51.png)

**Comment by SpoinkyNL** [comment]
Hey, thanks for the report! Could you try moving the fan back and forth a little by dragging it, dropping it and dragging it back again?

This might fix it and otherwise an Artemis restart might

Please let me know how it goes 😊

**Comment by pryankster** [comment]
yep.  it seems like moving the fan in the surface editor, after changing it's rotation does the trick.

**Comment by SpoinkyNL** [comment]
Hey, I've fixed this one, so with the latest version it should no longer be an issue.
