### ISSUE TITLE
[BUG] Unable to dl / install openrgb.

### ISSUE THREAD

**Issue by NicTanghe** [Artemis-RGB/Artemis#537]
Its ofc verry possible the server is just down but who knows here are my logs.
[Artemis log-20210203.txt](https://github.com/Artemis-RGB/Artemis/files/5914946/Artemis.log-20210203.txt)

**Comment by SpoinkyNL** [comment]
Hello,

The error is referring to the API server OpenRGB sets up while running, not any sort of download server.
Currently you need to install OpenRGB yourself, see the wiki for more info: https://wiki.artemis-rgb.com/en/guides/user/devices/open-rgb
