### ISSUE TITLE
Artemis - Startup wizard is not shown if the user denies Admin prompt

### ISSUE THREAD

**Issue by diogotr7** [Artemis-RGB/Artemis#546]
The MSI plugin (default) requires admin. This makes it so the user cannot use Artemis without giving it admin at least once. It also breaks the wizard since it's only shown on first startup.

**Comment by SpoinkyNL** [comment]
Fixed in https://github.com/Artemis-RGB/Artemis/commit/ac17658ec6e8b6a948f3169329fad61a53ee7e8d
