### ISSUE TITLE
G203 not working

### ISSUE THREAD

**Issue by wa-cool-69** [Artemis-RGB/Artemis#560]
My G203 mouse won't light up even though I have given Artemis control over it.

**Comment by SpoinkyNL** [comment]
I've already replied to you [here](https://github.com/Artemis-RGB/Artemis.Plugins/issues/23), please stick to that issue, thanks! :)

**Comment by wa-cool-69** [comment]
> I've already replied to you [here](https://github.com/Artemis-RGB/Artemis.Plugins/issues/23), please stick to that issue, thanks! :)

no i found that out, this is a different issue

**Comment by wa-cool-69** [comment]
I fixed that issue. Can you reopen this?

**Comment by wa-cool-69** [comment]
actually nevermind, I opened the other issue about the software and edited it.
