### ISSUE TITLE
Allow turning off/set to black on Application Exit

### ISSUE THREAD

**Issue by Chris-Barton** [Artemis-RGB/Artemis#561]
This is probably a feature request but could you add the ability for Artemis to turn of a device upon exit.

My use case for this is when my PC closes I want devices to be turned off as well.

This is especially important on devices where the lights are powered externally to the PC i.e Philips Hue, WS281XX Leds as they remain the their last state until the Application connects to them again. I've added a dirty temp fix for my system where I've change the Depose function in the CoreSerivice class to disable the device without saving 

**CoreService.cs**
```    
public void Dispose()
{
    _rgbService.Devices.ToList().ForEach(d => _rgbService.DisableDevice(d,false));
    // Dispose services
    _pluginManagementService.Dispose();
}
```

**RgbService.cs**

```

public void DisableDevice(ArtemisDevice device, bool save = true)
{
    if (!device.IsEnabled)
        return;

    _enabledDevices.Remove(device);
    device.IsEnabled = false;
    device.ApplyToEntity();
    if(save)
        _deviceRepository.Save(device.DeviceEntity);

    OnDeviceRemoved(new DeviceEventArgs(device));
}

```

Even if this was made configurable globally this seems quite inelegant functionality, it would be nice if you could configure each device separately allowing specific devices to be turned of when the application exits

**Comment by SpoinkyNL** [comment]
Hi there, 

During shutdown all plugins are disabled (and if implementing `IDisposed`, disposed) so any plugin has a chance to do something before Artemis shuts down.

However, many SDKs revert lighting to the state it was in before the Artemis plugin took control. This means that even if we set the device to 'all LEDs off' it will likely just reset again after the plugin finished disabling. Custom implementations such as WS281XX could be changed of course, either on the plugin side or on the Arduino (or whichever microcontroller is used) side.

In the case of Hue there are some options already: To change what colors your lights will be when Artemis releases control, open your Hue app head into: <LineBreak/> Settings > Entertainment rooms > Select your room > Behaviour when synchronization stops > Pick an option.

**Comment by Chris-Barton** [comment]
Specifically with WS281XX I did investigate changing the arduino code but there seems to be no easy way to detect if the serial connection is closed without introducing some sort of heartbeat. This would also be useful for things like DMX as they would remain in the last state if the connection was lost. 

If you can suggest the best way to add this feature to the WS281XX I don't mind implementing and testing it

**Comment by Chris-Barton** [comment]
I think to some extent looking at it it would benefit from running as a Windows service so that the led controller could intercept application exit/shutdown events. I may consider writing a plugin that supports LED controls over a COM or web protocol might be more widely useful

**Comment by SpoinkyNL** [comment]
Turning of the LEDs isn't incredibly complicated, it just has to happen outside the main Artemis render loop (which has stopped at the point of shutting down)

Modifying WS281XDeviceProvider.cs with the following should give you the desired result
```cs
public override void Disable()
{
    // Disable the LEDs on every device before we leave
    foreach (IRGBDevice rgbDevice in RgbDeviceProvider.Devices)
    {
        ListLedGroup _ = new(_rgbService.Surface, rgbDevice)
        {
            Brush = new SolidColorBrush(new Color(0, 0, 0)),
            ZIndex = 999
        };
    }
    // Don't wait for the next update, force one now and flush all LEDs for good measure
    _rgbService.Surface.Update(true);
    
    _rgbService.RemoveDeviceProvider(RgbDeviceProvider);
    RGB.NET.Devices.WS281X.WS281XDeviceProvider.Instance.Dispose();
}
``` 

If this works well I'm happy to add it as a setting to that device provider.

**Comment by Chris-Barton** [comment]
In my scenario im using 2 strips from one controller i.e appears as 2 devices. 

The fix above seems to be have pretty inconsistently sometimes it blanks both devices, sometimes it does only one and sometimes it remains on. 


I think this is to do with:

https://github.com/DarthAffe/RGB.NET/blob/master/RGB.NET.Devices.WS281X/Arduino/ArduinoWS2812USBUpdateQueue.cs

Because it uses a queue to process changes and events in multiple threads i think its not managing to flush the queue to the device before it get killed

**Comment by Chris-Barton** [comment]
Adding a short sleep helps
```
        public override void Disable()
        {
            // Disable the LEDs on every device before we leave
            foreach (IRGBDevice rgbDevice in RgbDeviceProvider.Devices)
            {
                ListLedGroup _ = new(_rgbService.Surface, rgbDevice)
                {
                    Brush = new SolidColorBrush(new Color(0, 0, 0)),
                    ZIndex = 999
                };
            }
            // Don't wait for the next update, force one now and flush all LEDs for good measure
            _rgbService.Surface.Update(true);
            Thread.Sleep(200);   // <<--------------------------------
            _rgbService.RemoveDeviceProvider(RgbDeviceProvider);
            RGB.NET.Devices.WS281X.WS281XDeviceProvider.Instance.Dispose();
        }
```

**Comment by Chris-Barton** [comment]
But this doesn't handle windows shutdown still

**Comment by Chris-Barton** [comment]
I think I've got it 
```
        public override void Disable()
        {
            // Disable the LEDs on every device before we leave
            foreach (IRGBDevice rgbDevice in RgbDeviceProvider.Devices)
            {
                ListLedGroup _ = new(_rgbService.Surface, rgbDevice)
                {
                    Brush = new SolidColorBrush(new Color(0, 0, 0)),
                    ZIndex = 999
                };
            }
            // Don't wait for the next update, force one now and flush all LEDs for good measure
            _rgbService.Surface.Update(true);
            Thread.Sleep(100);   // <<--------------------------------
            _rgbService.RemoveDeviceProvider(RgbDeviceProvider);
            RGB.NET.Devices.WS281X.WS281XDeviceProvider.Instance.Dispose();
        }
```

A 200ms works when the debugger is attached but not when running standalone is found 1s to be reliable

The to handle shutdown you can add

```
       protected override void Launch()
        {
            _applicationStateManager = new ApplicationStateManager(Args);
            Application.Current.SessionEnding += (object sender, SessionEndingCancelEventArgs e) => {
                _core?.Dispose();
            };

```

This event detects logout and shutdown allowing code be run before the app exits. Its the thing that causes the "Waiting for programs to close" on shut down

**Comment by SpoinkyNL** [comment]
Could you try with the following shutdown mechanism instead?
`Application.Current.SessionEnding += (_, _) => Core.Utilities.Shutdown();`

If that works as well, I'd rather use this :)

**Comment by Cheerpipe** [comment]
Handle windows shutdown is trivial, the problem here is the SDK could shutdown before artemis. For example, OpenRGB will close faster than Artemis on shutdown.

Logitech also has their own problem, it runs an agent that will set speakers to Audio Visualizer on windows shutdown.

Artemis may handle shutdown event very well but this is won't ensure leds will turn off. (sorry my english).

**Comment by Chris-Barton** [comment]
No this doesn't work not sure why.

Application.Current.Shutdown() dosen't seem to trigger the OnExit function of the Bootstrapper in this scenario 

I wonder certain events art trigger once a change off session occurs

**Comment by Cheerpipe** [comment]
If you can write your on light off switch, you can call it from here:

![image](https://user-images.githubusercontent.com/972765/112848980-02f83780-907f-11eb-827e-8970f7afffac.png)

**Comment by Chris-Barton** [comment]
The Application.Current.SessionEnding seems to work for my use case and also ensures that dispose() is called on the plugin tree un shutdown and logoff. 

@Cheerpipe I did think of this but it seems like application should handle this internally if it can. It can be very unreliable as windows doesn't allow multiple serial connections from different applications which means if this script is triggered before Artemis releases its handle it will fail.
At the very least it may be necessary for plugins to have dispose() even on shutdown/logoff which currently isn't the case.

@SpoinkyNL 
I'll try that now

**Comment by Chris-Barton** [comment]
Yer that worked I think this effectively two issues first that I wanted the WS281XX  to blank the Leds on Dispose and second that Dispose isnt called on Windows session exit.

**Comment by SpoinkyNL** [comment]
Perfect, I'll make the change to both the plugin and the shutdown mechanism then, thanks for testing 👍

**Comment by Chris-Barton** [comment]
My only concern would be on the WS281XX  would be the thread sleep is there a better way to flush the serial queue without just waiting and hoping it gets processed

**Comment by SpoinkyNL** [comment]
I'm not quite sure how this is implemented but we could try removing the delay and specifically updating the devices
I have no hardware to test with but this might work reliably:
```cs
public override void Disable()
{
    // Turn off the LEDs on every device before we leave
    if (_settings.GetSetting("TurnOffLedsOnDisable", true).Value)
    {
        foreach (IRGBDevice rgbDevice in RgbDeviceProvider.Devices)
        {
            ListLedGroup _ = new(_rgbService.Surface, rgbDevice)
            {
                Brush = new SolidColorBrush(new Color(0, 0, 0)),
                ZIndex = 999
            };
        }
        // Don't wait for the next update, force one now and flush all LEDs for good measure
        _rgbService.Surface.Update(true);
        
        // Force devices to update straight away
        foreach (IRGBDevice rgbDevice in RgbDeviceProvider.Devices) 
            rgbDevice.Update(true);
    }

    _rgbService.RemoveDeviceProvider(RgbDeviceProvider);
    RGB.NET.Devices.WS281X.WS281XDeviceProvider.Instance.Dispose();
}
```

**Comment by Chris-Barton** [comment]
This seems to work but I think this is one of those timing issues that wouldn't be verifiable till there is a proper build

I'd be happy to test it out properly an "Release Build"

**Comment by SpoinkyNL** [comment]
With the latest version I've added the setting to the plugin.
![image](https://user-images.githubusercontent.com/8858506/112978955-3eb30000-9158-11eb-85d0-d8a0d1206111.png)

When you close the window settings you may need to restart Artemis to avoid an unrelated RGB.NET bug.

**Comment by Chris-Barton** [comment]
This seems to work perfectly. Thankyou very much for your effort
