### ISSUE TITLE
Gradient picker - Add spread equally button

### ISSUE THREAD

**Issue by SpoinkyNL** [Artemis-RGB/Artemis#564]

**Comment by Cheerpipe** [comment]
A "Close gradient" button could also be nice to add automatically the start color to the end (and compress the gradient steps maintaining the distant relation).

**Comment by SpoinkyNL** [comment]
Not sure what you mean, could you create an example before and after?

**Comment by KnottyDyes** [comment]
Alternatively, you could just ask how many steps in the gradient you want, and it plops them all in, equidistant from each other.

**Comment by Cheerpipe** [comment]
> A "Close gradient" button could also be nice to add automatically the start color to the end (and compress the gradient steps maintaining the distant relation). (Similar to the Aurora's "Seamles gradient" but better)



> Not sure what you mean, could you create an example before and after?

I PR an example implementing a "repeat seamless" mode for linear gradient.

**Comment by SpoinkyNL** [comment]
Closed by #586
