### ISSUE TITLE
Profiles - Restructure

### ISSUE THREAD

**Issue by SpoinkyNL** [Artemis-RGB/Artemis#572]
The current structure of modules needs some rethinking. Right now each module is represented in the sidebar and can have multiple profiles.

I question the use of this, you create a profile for a module once and then stick with that. Swapping profiles is cumbersome and generally not something you'd do.

I think it would be better to ditch the idea of profiles being tied to a module, instead let's tie modules to profiles. 
### A few key differences
- Removes the limitation of one profile active per module
- Adds the ability to add profiles without them being tied to any module in any way
- This makes the overlay and general module, which have always felt weird to me, redundant
- Provides good entry point for activation conditions, allowing you to create profiles per game/application in a self-contained environment and provide activation via keybinds

This still allows you to create multiple profiles per module but a key difference will be in how they are presented and the customization they will offer.

As for modules code, it'll lose the ability to do any rendering, it will merely serve as a container for game data

The sidebar will simply be a categorized list of profiles (probably slightly more condensed) we can even let people come up with their own categories.

### Some potential issues
- Performance, we need a way to detect that rendering a profile is useless when it is fully overlapped by another profile
  - In that spirit we should also update hidden profiles less frequently (we have delta time after all)
- How to handle non-profile modules? They still offer some flexibility for plugin devs which I'd rather not lose.
- Should modules (while their activation req. is met) always be updating or only when they have active profiles? Profiles may activate depending on certain data model conditions provided by said module.
  - The [DataModelPath](https://github.com/Artemis-RGB/Artemis/blob/master/src/Artemis.Core/Models/Profile/DataModel/DataModelPath.cs) could let the [DataModel](https://github.com/Artemis-RGB/Artemis/blob/master/src/Artemis.Core/Plugins/DataModelExpansions/DataModel.cs) know they're watching.. That can bubble up through the data model to the root, so the module knows it's data is being used.
- How will key bindings work, once a keybind is matched, deactivate all other profiles with a keybind?

**Comment by DJMalachite** [comment]
I like the idea of having a centralized place for a profile 

maybe you could make a layer option that says whether the layer (or folder) is supposed to render for Overlay or background use

**Comment by SpoinkyNL** [comment]
> maybe you could make a layer option that says whether the layer (or folder) is supposed to render for Overlay or background use

Wouldn't this get a little confusing?
I think profiles will render in order, first by category and then by profile. That way if you want something to be on top, you put it in a profile which is on top, seems the most intuitive to me.

**Comment by DJMalachite** [comment]
> d

I see how that could get confusing I misunderstood the method at hand I retract my idea :)

**Comment by SpoinkyNL** [comment]
Just writing down my thoughts about profile keybinds

**When a keybind is matched do the following, based on config**
- Enable the profile & disable all other profiles with a keybind
- Enable the profile & disable all other profiles in the same category with a keybind
- Toggle the profile, leaving others alone

**Comment by Cheerpipe** [comment]
And don't forget an api to enable disable profiles :D

**Comment by SpoinkyNL** [comment]
Kai's concepts, I won't be copying these 1 on 1 but they serve as inspiration
![ArtemisMain](https://user-images.githubusercontent.com/8858506/119620659-875c0200-be05-11eb-9c04-71540015ddb4.png)
![ArtemisSidebar](https://user-images.githubusercontent.com/8858506/119620676-8c20b600-be05-11eb-94f9-630d74a8a3f5.png)

**Comment by AlpacaFur** [comment]
Here are a few more concepts for inspiration I posted on the Discord a while ago:

![Layout Ideas](https://user-images.githubusercontent.com/2746893/119756033-ed31a380-be70-11eb-8408-0f673f86c915.png)
![Sidebar with Conditions](https://user-images.githubusercontent.com/2746893/119756035-ed31a380-be70-11eb-812d-ebd7a125a0de.png)
![Sidebar](https://user-images.githubusercontent.com/2746893/119756036-edca3a00-be70-11eb-92a9-791d6259a2c6.png)
![Timeline](https://user-images.githubusercontent.com/2746893/119756037-edca3a00-be70-11eb-950d-a6c0bb1e823a.png)
