### ISSUE TITLE
Plugins - Profiling API

### ISSUE THREAD

**Issue by SpoinkyNL** [Artemis-RGB/Artemis#578]
Plugins should have means to profile themselves in various areas
I think something like `StartMeasure(string identifier)` and `StopMeasure(string identifier)`.

We can have plugins call these as they like but we'll also call them in `Update()` and `Render()` so that it's easy to expand but has some default measurments by default.

The debugger will then show min, max, average and 95th percentile per plugin and per identifier.
I'm not sure how much data we should store and perhaps we should only collect data while the debugger is open.

**Comment by Cheerpipe** [comment]
> I'm not sure how much data we should store and perhaps we should only collect data while the debugger is open.

Or use a startup param to enable profiling to collect more "real life" like data without the opened debugger .

**Comment by SpoinkyNL** [comment]
This is now implemented
