### ISSUE TITLE
Surface Editor - Color calibration is not applied when calibrating

### ISSUE THREAD

**Issue by diogotr7** [Artemis-RGB/Artemis#579]
If the UI is closed, the calibration is applied to the regular profiles. But when editing in the device properties window, it is not.

**Comment by diogotr7** [comment]
I tested this further:
* When "Show random device colors" is ticked, no changes can be seen when adjusting the sliders.
* When the option is *not* ticked, the changes can be seen on the physical device, but not on the UI.

**Comment by SpoinkyNL** [comment]
Fixed by flushing LEDs
