### ISSUE TITLE
Profile Editor - Top and bottom repeat options are out of sync

### ISSUE THREAD

**Issue by Cheerpipe** [Artemis-RGB/Artemis#585]
These two options are out of sync when changing the top one.

![image](https://user-images.githubusercontent.com/972765/115928095-95f47980-a453-11eb-94e8-f01efb671143.png)

![unknown](https://user-images.githubusercontent.com/972765/115928004-680f3500-a453-11eb-8f33-890de4b29406.png)

**Comment by SpoinkyNL** [comment]
Fixed next update :)
