### ISSUE TITLE
UI - Multiple Artemis.UI.exe processes remaining alive 

### ISSUE THREAD

**Issue by SpoinkyNL** [Artemis-RGB/Artemis#602]
Not sure what the deal is with this, but it's happening to multiple people

**Comment by AlpacaFur** [comment]
I can repro this by exiting Artemis via the System Tray icon and then quickly reopening it before the process fully exits (which takes ~2 seconds for me). The result of this is the process stays alive, but the icon is gone from the system tray and the app doesn't open. On each attempted opening past that point, another process is spun up, but nothing else happens.

**Comment by SpoinkyNL** [comment]
Fixed in https://github.com/Artemis-RGB/Artemis/commit/38c04913e2cfb1f1ec62f353cd686ba26f79d395
