### ISSUE TITLE
Is Linux support planned at some point?

### ISSUE THREAD

**Issue by The-Linux-User** [Artemis-RGB/Artemis#622]
The title pretty much says it all, would be nice if this plugin could be cross platform like OpenRGB

**Comment by SpoinkyNL** [comment]
Hey,

As per our [FAQ](https://wiki.artemis-rgb.com/en/faq#q-will-artemis-be-cross-platform)

> Q: Will Artemis be cross platform?
> A: Maybe. The core is written in .NET Core and can be compiled for Linux with minimal changes.
> The UI is a different story, it is written in WPF which is a Windows-only platform. Artemis can function without the UI though and a different UI based on cross-platform frameworks can be put in place as well. I don't currently have any plans to do this but perhaps when Artemis 2 has matured enough and is feature complete, it would be a nice endeavour.
> 
> There is also the option of running Artemis in Wine, with which some users on Discord had succes in combination with the OpenRGB plugin.

**Comment by RobertBeekman** [comment]
I noticed this issue is pinned but outdated.

Native Linux support is being worked on on the Avalonia branch: https://github.com/Artemis-RGB/Artemis/tree/feature/avalonia :)

You can also track the progress here:
https://github.com/orgs/Artemis-RGB/projects/1

**Comment by agentwolf88** [comment]
Any news about the linux port? Is there now a way to use it in linux?

**Comment by RobertBeekman** [comment]
@agentwolf88 the Avalonia update is in it's final testing phase for Windows right now.
After that focus will shift to making sure everything works well on Linux too (no major issues expected)

**Comment by NicTanghe** [comment]
Gr8 news finally things that work everywhere.

**Comment by diogotr7** [comment]
I'm working on linux packaging but in the meantime here's a build you can try: https://builds.artemis-rgb.com/binaries/linux-ci/20220820.2/artemis-build-linux.zip

any feedback appreciated!

**Comment by agentwolf88** [comment]
> I'm working on linux packaging but in the meantime here's a build you can try: https://builds.artemis-rgb.com/binaries/linux-ci/20220820.2/artemis-build-linux.zip
> 
> any feedback appreciated!

How can i use this. I use Manjaro Linux and i am a newby.

**Comment by LMH01** [comment]
> > I'm working on linux packaging but in the meantime here's a build you can try: https://builds.artemis-rgb.com/binaries/linux-ci/20220820.2/artemis-build-linux.zip
> > any feedback appreciated!
> 
> How can i use this. I use Manjaro Linux and i am a newby.

Download the file, unzip it, open a terminal in the unzipped folder and enter `./Artemis.UI.Linux`.

**Comment by Bitwolfies** [comment]
Im curious, will the wrappers to auto convert integrated game support work over wine?

**Comment by Bitwolfies** [comment]
Also, where is the config for the linux build? I  was testing and ran into a crash, and I have not been able to get it to restart after, so I assume it left a config somewhere, I just cant find it.

**Comment by NicTanghe** [comment]
hallokes kan ik nog ergens een linux binary of appimage of rpm vinden ?

**Comment by RUGMJ** [comment]
Are there any updates on this?

**Comment by RobertBeekman** [comment]
We've had several users had success with our Linux builds, you can find the download link on https://artemis-rgb.com/
If you do run into any specific issues please hit us up on Discord or create a new issue here :)

**Comment by diogotr7** [comment]
Here's a quick install script that should work and allow Artemis to auto update itself: https://github.com/Artemis-RGB/Artemis/pull/770

We are also considering offering proper Linux packages but none of us core developers are very experienced with that. If anyone wants to help with this join our discord.
