### ISSUE TITLE
Add a rendering option to not take average but dominant color or only center of the led

### ISSUE THREAD

**Issue by Cheerpipe** [Artemis-RGB/Artemis#628]
Darth Affe: it might be reasonable to add a rendering option to not take average but dominant color or only center of the led for those who want it
[11:09] Darth Affe: but that would be a setting for everything not just the visualizer

This could also help with bleedeng in some big surfaces and give some extra performance at the same time (take just the center pixel)?

**Comment by DarthAffe** [comment]
The performance gain would be minimal in most cases (rendering is way more expensive than sampling) but bleeding should be gone with center only.

**Comment by RobertBeekman** [comment]
With the recent fixes to LED bleeding I'd say this is no longer necessary. 
Feel free to re-open if there's another good reason to have this :)
