### ISSUE TITLE
Exe Detected as Malware by SEP

### ISSUE THREAD

**Issue by georgethemarmot** [Artemis-RGB/Artemis#631]
Antivirus Symantec Endpoint Protection 14.3 is detecting 
https://builds.artemis-rgb.com/binaries/Artemis.Installer.exe
as Malware

![image](https://user-images.githubusercontent.com/4931142/123669841-d352fa00-d83c-11eb-9f87-41a8921aedd0.png)

**Comment by EddwardR** [comment]
Isn't that software enterprise exclusive? It's probably against company policy to install stuff like Artemis

**Comment by SpoinkyNL** [comment]
Hey there,

Unfortunately there's not much I can do about this false positive other than paying a large yearly sum of money for a code signing certificate. 

A VirusTotal scan should clear things up :) https://www.virustotal.com/gui/url/be727416ede53be91294b7585481ca5b0cfa666e0976d092e842ae5c47b276ea/detection

**Comment by georgethemarmot** [comment]
> Isn't that software enterprise exclusive? It's probably against company policy to install stuff like Artemis.
> Also, dropping what signature it's finding would be very helpful

Company policy has nothing to do with the detection as the identification of the category is "Malware"

--

I dropped the information not expecting resolution.

**Comment by SpoinkyNL** [comment]
I'm leaving this up as a pinned issue for future reference
