### ISSUE TITLE
Question about Xbox XB1ControllerBatteryIndicator

### ISSUE THREAD

**Issue by lmills87** [Artemis-RGB/Artemis#643]
Hello - I know this is completely out of line and not the proper place to ask this but I noticed that the issues had been closed on XB1ControllerBatteryIndicator and I knew of no other way to contact you.

I starting using XB1ControllerBatteryIndicator and I love it, however, I have two suggestions for improvement (if you're at all willing to entertain them at this point):

1. A visual/text indicator of low battery that displays in the Window notifications or otherwise (as opposed to just an audio warning)

2. An option to "turn controller off" when right-clicking the icon in the system tray. It would be faster than having to wait 10 seconds (to hold the button down on the controller) and I prefer to not rip the battery out, although sometimes this is actually necessary as holding the button down doesn't work and causes the controller to start syncing or something (at which point removing the battery seems to be the only way to turn it off).

Anyways, this would be my most desired feature; a simple way to just turn the controller off in the system tray options.

Also, not sure if this is actually an issue or not but I've noticed that sometimes the notification (when I mouse over the icon to check battery percentage) gets partially obscured by the task bar (like it appears behind it instead of in front of it).

Thanks for any consideration you might give this and I apologize for disrupting the flow here but assume you can delete this at will if needed.

**Comment by SpoinkyNL** [comment]
Hi there,

I'm no longer maintaining that and don't really have the time to do so either, sorry!
There's a fork though that might have the features you need, looks like it has a notification at least.

You can find it here:
https://github.com/NiyaShy/XB1ControllerBatteryIndicator

Good luck!
