### ISSUE TITLE
Corsair Virtuoso SE Mic LED Not Detected

### ISSUE THREAD

**Issue by Sturmx88** [Artemis-RGB/Artemis#645]
Artemis RGB detects my Corsair Virtuoso but the SE version and normal are the same in the program. The SE version has an LED around the mic that can be disabled in iCUE but when iCUE is closed it lights up as a bright green circle. I dug through my iCUE profile to see if I can find it and I did.  
![image](https://user-images.githubusercontent.com/88456591/128239065-1184b728-2f1d-453c-9922-eb922acb2a85.png)

That's about as far as I've gotten with my very limited knowledge. I should be able to find everything about it in my iCUE profile. Is there any way for me to find that in Artemis? Maybe using my iCUE profile or something else? Would really like to use Artemis, I've had problems with iCUE for a long time.

**Comment by SpoinkyNL** [comment]
Hey, I don't think that LED is controllable as the headset uses it to indicate mic mute status.
I have a regular Virtuoso and I'm sure that this is the case for that, I imagine the same goes for the SE version

**Comment by Sturmx88** [comment]
Oh really. Figured if you are able to turn it off and on in iCUE that you could likely here as well. Back to looking for an iCUE alternative. The Mic LED, when not ran through iCUE, gives
