### ISSUE TITLE
Logitech G915 TKL Support

### ISSUE THREAD

**Issue by Will-Dower** [Artemis-RGB/Artemis#648]
Hi,

I've been trying to get my Logitech G915 TKL wireless keyboard to work with Artemis but haven't been having much luck. In wireless mode, it displays "Logitech Lightspeed Dongle" and in wired mode it displays G915 TKL, but in both it recognises no LEDs at all.

I noticed as of the current RGB.NET development branch, the 915 TKL's PID is listed (0xC343), so I tried downloading the latest build, but that hasn't worked either. I also attempted to build from source using the development branch using the readme steps, but neither Artemis nor Artemis.Plugins compiled without errors (perhaps I'm using the wrong version of .NET?)

If there's any steps you can give me to compile properly/other steps to follow please let me know! Cheers!

**Comment by SpoinkyNL** [comment]
Hi there,

Unfortunately Logitech devices do not function without a layout file. 
For the G915 TKL I suggest you try loading the default TKL layout. You can do this by going into **Settings** > **Devices**, locate your keyboard and click on the **three dots** to open **Properties**

From click on Layout and paste 
`C:\Program Files\Artemis\DefaultLayouts\Artemis\Keyboard\Artemis TKL keyboard-ANSI.xml` or
`C:\Program Files\Artemis\DefaultLayouts\Artemis\Keyboard\Artemis TKL keyboard-ISO.xml`, depending on your keyboards layout

The idea is that this would happen automatically but that functionality is currently broken for Logitech.

**Comment by diogotr7** [comment]
This should be fixed by https://github.com/DarthAffe/RGB.NET/pull/238
