### ISSUE TITLE
Wonky WLED device layouts

### ISSUE THREAD

**Issue by ikrowni** [Artemis-RGB/Artemis#650]
When i have the render scale set to 100% all seems to be fine

![Capture](https://user-images.githubusercontent.com/4442098/128912760-6b6f1187-8704-421b-a985-875d3def0973.PNG)

But if i change it to anything else the lights get rainbow colored and become unresponsive.

![Capture](https://user-images.githubusercontent.com/4442098/128912961-ede3da61-d7cb-4d41-9b68-9e525f85dce3.PNG)

Here are the layouts i've created for my WLED devices

[LedStripe-layouts.zip](https://github.com/Artemis-RGB/Artemis/files/6963635/LedStripe-layouts.zip)

**Comment by SpoinkyNL** [comment]
As a workaround: Changing the layouts to use a LED size of 6 fixes the issues on a 50% render scale, going to 25% will still give issues.

Still not certain how to fix this so will leave this open as the layouts are also useful for testing.

**Comment by ikrowni** [comment]
Is there a way to quickly adjust the size of all LEDs?

**Comment by SpoinkyNL** [comment]
Yes, change the default LED width and height. It should only be 2 edits per layout.

**Comment by ikrowni** [comment]
> Yes, change the default LED width and height. It should only be 2 edits per layout.

![Screenshot 2021-08-14 140339](https://user-images.githubusercontent.com/4442098/129456327-c4c62372-cac0-4d4e-b58a-b18ff3027f75.png)

Changed the defaults to 6x6 and then click save but when i reopen the layout its back to 5x5 again

**Comment by SpoinkyNL** [comment]
You can change it in the XML files too, it's on line 10 and 11

```xml
  <LedUnitWidth>8</LedUnitWidth>
  <LedUnitHeight>8</LedUnitHeight>
```

**Comment by ikrowni** [comment]
Excellent 50% scale working great now.

![Screenshot 2021-08-14 140339](https://user-images.githubusercontent.com/4442098/129460986-d0886b74-b9d9-4d09-a64a-ef5a70181522.png)

**Comment by RobertBeekman** [comment]
Since this issue was created I've made some vast improvements to rendering at different scales.
You should even have success at 25% now (which is the new default)
