### ISSUE TITLE
Artemis is causing the Nvidia driver to crash

### ISSUE THREAD

**Issue by HunterAhlquist** [Artemis-RGB/Artemis#651]
I have a 3070, and **only** when Artemis has a window open it lags intensely at first then crashes the Nvidia driver every time the window attempts to draw. 

Windows ver: 21H1
Artemis ver: the latest as of the time of writing this, I am unable to check through the app because of the above issue
Nvidia driver ver: 471.68

Windows event view log:
`Faulting application name: Artemis.UI.exe, version: 2.0.0.0, time stamp: 0x60e896d9
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1151, time stamp: 0x891df6d3
Exception code: 0xc000041d
Fault offset: 0x0000000000034ed9
Faulting process id: 0x3680
Faulting application start time: 0x01d7965dbc250ca7
Faulting application path: C:\Program Files\Artemis\Artemis.UI.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 5ddfcd82-3780-43b4-9fd5-217c2888d9c6
Faulting package full name: 
Faulting package-relative application ID: `

Artemis log:
[Artemis log-20210821.log](https://github.com/Artemis-RGB/Artemis/files/7025102/Artemis.log-20210821.log)

**Comment by SpoinkyNL** [comment]
Hi, I see your logs is full of WPF-related errors. Please try a clean driver install using [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html)
