### ISSUE TITLE
Artemis doesn't detect G502 mouse connected to logitech Powerplay mat

### ISSUE THREAD

**Issue by ecast040** [Artemis-RGB/Artemis#652]
As mentioned, when I start up Artemis it doesn't detect my G502 wireless mouse when connected through Logitech Powerplay mat and it doesn't detect the RGB of the Powerplay mat either.

**Comment by SpoinkyNL** [comment]
Hi, this is a limitation of the Logitech SDK

Plugin developer @Cheerpipe has made a plugine that talks directly to Powerplay devices without the SDK, you can give that a shot.

I couldn't find a link on his repository but he posted it in our Discord here https://discordapp.com/channels/392093058352676874/765274077513383936/859618430116954122

**Comment by diogotr7** [comment]
I'm still looking into a way to read this information off of wireless dongles. Currently the main issue is communicating with the device while ghub is also communicating with it. I don't think there's any foolproof way of exclusively accessing the device so I might have to retry the connection until I get good information.

**Comment by Cheerpipe** [comment]
In the meantime i may add an option to manually set the mouse connected to the mat in order to apply the correct layout and led count.

**Comment by SpoinkyNL** [comment]
That's not an unreasonable limitation though, just look at what happens when you run both ORGB and manufacturer software at the same time, it's never pretty.

**Comment by diogotr7** [comment]
G502 detection should be fixed by https://github.com/DarthAffe/RGB.NET/pull/238
