### ISSUE TITLE
Hotkeys - key presses registering on key up, not key down

### ISSUE THREAD

**Issue by iGerman00** [Artemis-RGB/Artemis#657]
Hotkeys react to key up, not key down, here, I want Alt+Ctrl+Shift+B, I am pressing them in this order in the video I attached :
ctrl down, shift down, alt down, b down, b up (shows correct hotkey at this point), ctrl up, shift up, alt up -> wrong hotkey captured

https://user-images.githubusercontent.com/36676880/132997568-81d0b143-8f58-4ef2-a341-5593bc615906.mp4

I worked around this by pressing "Accept" before releasing ctrl, shift and alt.

**Comment by RobertBeekman** [comment]
Fixed, thank you for the explanation
