### ISSUE TITLE
Can't enable Corsair Device Provider

### ISSUE THREAD

**Issue by Adrelyr** [Artemis-RGB/Artemis#659]
Welp, the issue is in the title.
I tried Artemis some time ago and already ran into this issue. I don't see any issue concerning this problem on github so it may be related to my computer.
I have a Corsair Strafe RGB MK2 and  iCUE isn't installed. (I do have Logitech G hub for my headset and mouse)
Fresh install of windows and Artemis
[Artemis log-20210915.log](https://github.com/Artemis-RGB/Artemis/files/7170274/Artemis.log-20210915.log)
![image](https://user-images.githubusercontent.com/34719169/133438923-43d7c381-ff6a-4507-b0ce-f54cd8dc0dca.png)

**Comment by diogotr7** [comment]
Artemis doesn't communicate with hardware by itself. You'll need to install iCUE and enable the sdk option in the settings.

Alternatively, OpenRGB might work depending on your specific peripheral models.

**Comment by Adrelyr** [comment]
> 
> 
> Artemis doesn't communicate with hardware by itself. You'll need to install iCUE and enable the sdk option in the settings.
> 
> Alternatively, OpenRGB might work depending on your specific peripheral models.

Ah I see. Would be cool to see it mentioned for noobs like me in all that is RGB 😁 (or it already is and I really need to improve on reading stuff 😅)
