### ISSUE TITLE
Corsair plugin not working

### ISSUE THREAD

**Issue by Artemis5208** [Artemis-RGB/Artemis#661]
First time using Artemis, was trying to get it working for my K70 RGB (because iCUE sucks lol) but it won't allow me to install the plugin to support Corsair hardware. Is this a known issue and if so could I have the solution to fix this please?

I've attached the log below, latest entry is from trying to install the plugin (NOTE: I do have iCUE running in the background at the time of the log error)
[Artemis log-20210921.log](https://github.com/Artemis-RGB/Artemis/files/7206218/Artemis.log-20210921.log)

**Comment by diogotr7** [comment]
Check that you have the SDK enabled in the iCUE settings.
