### ISSUE TITLE
README build instructions do not work with Visual Studio 2019

### ISSUE THREAD

**Issue by doxxx** [Artemis-RGB/Artemis#672]
The build instructions in the README don't work with Visual Studio 2019 because the current version of RGB.NET requires .NET 6, or at the very least C# 10.

**Comment by diogotr7** [comment]
The last RGB.NET commit that works with Artemis is `2b64773c479a83bb78e6792717e2f428731c4e2c`, which is what I've changed my CI scripts to use. Artemis will use NET 6 soon hopefully.

**Comment by RobertBeekman** [comment]
We now use NuGet packages to reference RGB.NET (for now) VS19 will work again.
When we do move Artemis to .NET 6 I think we'll lose VS19 support for good.
