### ISSUE TITLE
Artemis does not detect my Cooler Master CK550 V2

### ISSUE THREAD

**Issue by NemzetkoziPank** [Artemis-RGB/Artemis#681]
title says it all

**Comment by diogotr7** [comment]
CoolerMaster never added support for this keyboard in their SDK. The regular ck550 works but the v2 does not.

**Comment by NemzetkoziPank** [comment]
oh, i see, do i have any alternatives to MasterPlus? Its  literally unusable.

**Comment by diogotr7** [comment]
Maybe try OpenRGB, might be supported. If OpenRGB works, you can also use Artemis with it.
