### ISSUE TITLE
How to interact with Artemis with Javascript

### ISSUE THREAD

**Issue by SpyGuy0215** [Artemis-RGB/Artemis#707]
In Artemis, there is a Javascript scripting plugin. Is that functional/how do I use it to interact with my devices?

![image](https://user-images.githubusercontent.com/57506946/182943749-0552936c-fc28-4f66-be8c-fa5518726882.png)

**Comment by RobertBeekman** [comment]
Hello,

There currently isn't a guide for scripting but you can create scripts in the editor under File > Scripts
The editor has auto-complete which you can use to view possible APIs

**Comment by SpyGuy0215** [comment]
Alright, thanks so much
