### ISSUE TITLE
MQTT Control

### ISSUE THREAD

**Issue by PartemImperium** [Artemis-RGB/Artemis#710]
It would be nice if in addition to the local API if Artemis could be controlled by subscribing to MQTT topics. My main use for this would be so I could easily control suspending a profile from Home Assistant however I'm sure anything that the API does would be useful as MQTT control  for people.

**Comment by Dobarekk** [comment]
Yes please. Maybe add Options to make Artemis Mqtt wake your pc, put it to sleep, some media functions or sth like that.

**Comment by PartemImperium** [comment]
I don't think Artemis would be a good spot to do MQTT Pc Wake/sleep/media functions. If that is what you want there are already solutions that do that. IoTLink, HASS.Agent etc.

**Comment by sclark-dev** [comment]
MQTT integration would be great. Just the ability to set LED color based on MQTT would be helpful, but the ability to use them in conditions too would be amazing.

**Comment by diogotr7** [comment]
@Wibble199 Wrote a plugin like this for the Wpf version of Artemis, I've ported it and published it here: https://github.com/Artemis-RGB/Artemis.Plugins.Mqtt

My knowledge of mqtt is quite limited so it might be broken, but it's a start.

In short, you can choose values that will be updated. You can then use this data in artemis however you want.

Any issues with the plugin should be made in that repository, so I'll close this issue.
