### ISSUE TITLE
Numeric easing node always outputs 0

### ISSUE THREAD

**Issue by lukereative** [Artemis-RGB/Artemis#721]
If I add a numeric easing node and connect everything up, the output is always 0 (both in the node editor and the connected value), even when the timeline is playing.
![image](https://user-images.githubusercontent.com/1415622/187009659-4704cec1-bf1d-4d9b-b6ee-0a0a042b8814.png)

**Comment by RobertBeekman** [comment]
Hi, thanks for the report

This was fixed in https://github.com/Artemis-RGB/Artemis/commit/cf58acc7d2792a4cd18f704cb0ce502dce867aaf
