### ISSUE TITLE
Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by Thepyrocrafteur** [Artemis-RGB/Artemis#771]
### When

After updating Artemis using the in-app updater

### What

Windows Defender blocked some files and the installer, reporting as `Trojan:Script/Wacatac.B!ml` twice with **severe level**

![image](https://user-images.githubusercontent.com/7360624/228028367-3505db56-a18b-4676-80d6-05714cd358ba.png)

### Version

Artemis 1.2023.0326.9

**Comment by diogotr7** [comment]
We were discussing this in the discord server: It's a false positive. We didn't change the installer very much, so I'm not sure why Defender is flagging it. Maybe it will return to normal once more people have downloaded it.
