### ISSUE TITLE
[ENHANCEMENT] Add the possibility to share profile layout

### ISSUE THREAD

**Issue by Chewbaka69** [Artemis-RGB/Artemis#773]
Add the ability to us to share our layout with a single button (share, export, send to libraries)

Maybe having like a free store to list all the user layout, allow other to easily import it from the software.

Thanks for your work :)

**Comment by RobertBeekman** [comment]
Hi, sorry for not getting back to you.

This is planned as part of our workshop, I've laid out our future plans on [Discord](https://discord.com/channels/392093058352676874/1010581788466368522/1059075910147514378) :)
