### ISSUE TITLE
Layers getting corrupted

### ISSUE THREAD

**Issue by diogotr7** [Artemis-RGB/Artemis#775]
I'm not exactly sure why this happens but here you go:

Sometimes, layers will be left in an unusable state where the layer brush cannot be selected. It will revert back to `null`. Only deleting the layer and creating a new one will fix this.

Testing a corrupted database gave me some information:
`Layer.LayerBrush` is Correct. In my example, it contained information relative to a solid brush
`Layer.GeneralPropertyGroup.BrushReference` is incorrect. The `BrushReference` identifier is set, but the Value is `null`.

I have a database where this is an issue, but I can't post it here because it contains sensitive information.

**Comment by RobertBeekman** [comment]
Fixed by 3b04447ff71366055e6dae48c88b7a1fb9d43501
