### ISSUE TITLE
Wrong key in preset config

### ISSUE THREAD

**Issue by totchi-lagawi** [Artemis-RGB/Artemis#776]
Hi there!
I have an issue with the hotkeys function to enable/disable a preset. When I try to use it, Artemis will see a wrong input (when I press "Space", it sees "Insert"). This also happens in the script editor, but not anywhere else. I tried to completely uninstall/reinstall it, but the problem is still here. This doesn't happen with the previous release.

**Comment by diogotr7** [comment]
I figured out what happendd, fixing

**Comment by totchi-lagawi** [comment]
Thanks

*(Reactivity : **O_O**)*
