### ISSUE TITLE
WS281X Devices option not saving any information

### ISSUE THREAD

**Issue by euwlo31** [Artemis-RGB/Artemis#777]
After clicking the "Accept" button to add a new device in the WS281X plugin settings, 
the new device is always named "Device X", of type Arduino and without a COM port or hostname
Also, the same when trying to edit a device.

Fresh install 
1.2023.0412.1
12/04/2023 15:52

**Comment by DarthAffe** [comment]
The same seems to happen for the DMX-plugin
