### ISSUE TITLE
[Bug Report] Crash when drawing custom layout

### ISSUE THREAD

**Issue by umbreon222** [Artemis-RGB/Artemis#781]
### Version
1.2023.0414.7

### Description
Started noticing Artemis crashing consistently whenever I navigated to the surface editor or the properties of this particular device. From the log alone, it looks like it's crashing trying to draw some geometry.

[CustomUserLayout.zip](https://github.com/Artemis-RGB/Artemis/files/11252555/CustomUserLayout.zip)
[Artemis log-20230417.log](https://github.com/Artemis-RGB/Artemis/files/11252489/Artemis.log-20230417.log)

**Comment by RobertBeekman** [comment]
Hi there,

Thanks for the report. In some cases we cannot process the geometry from the layout file and when that happens we should simply skip that LED, not crash. I've fixed that issue and now you'll simply not see the broken LED.

In your case `Keyboard_Custom13` is the broken LED, copy-paste mistake perhaps? 
```xml
    <Led Id="Keyboard_Custom13">
      <Width>1.1a1.15</Width>
      <Height>0.25</Height>
    </Led>
```
