### ISSUE TITLE
Input events does not triggered in some games

### ISSUE THREAD

**Issue by voed** [Artemis-RGB/Artemis#806]
For example, `Uncharted: Legacy of thieves` intercepts all input events from keyboard/mouse, so my "turn off the backlight while idle" script is being activated. There are some more games with same behaviour, but i cannot remember them for now. Will report them later.

Win 11, Artemis 1.2023.0727.9
p.s. also it would be great to have a possibility to copy version number from the "About" page

**Comment by RobertBeekman** [comment]
This is not something we can really change without making input capture way more invasive to a point where it's on par with keyloggers.

Some games and applications prevent input events from bubbling up, usually for security reasons. Firefox per example does this when you type in a password field.

What may help is this: https://github.com/Artemis-RGB/Artemis.Plugins/commit/fe79cb61122bea3e60ec60a58060a4e511b84235
I've added a new IsFullscreen property to the active window data model, you could use that to make your idle script a bit smarter
