### ISSUE TITLE
Corsair K100 RGB-ISO support

### ISSUE THREAD

**Issue by MeurglysIII** [Artemis-RGB/Artemis#816]
Please, add support for **Corsair K100 RGB-ISO**. Now the default layout path is the following: **"C:\ProgramData\Artemis\Plugins\Artemis.Plugins.Devices.Corsair-926629ab\Layouts\Corsair\Keyboard\K100** RGB-ISO.xml", but there is no such file in that folder. I solve it by renaming the file "K100-ISO.xml" to "K100 RGB-ISO.xml", but every time Artemis updates, this file is deleted. Just adding a copy of "K100-ISO.xml" with the name "K100 RGB-ISO.xml" would solve the issue. Thanks!
![image](https://github.com/Artemis-RGB/Artemis/assets/41144285/cd20bd6e-0ced-42f2-9039-7fc443c26ee3)
![image](https://github.com/Artemis-RGB/Artemis/assets/41144285/65484f46-6529-4115-9edd-df8bf9cf5221)

**Comment by lilman2727** [comment]
Try moving the edited .xml file along with the corresponding image to **C:\ProgramData\Artemis\User Layouts**. There, make a folder (for organization's sake) named Corsair and put the .xml and image into it.
Then. in Artemis, navigate to the screen on the screenshot you've provided, click the Browse button and navigate to the folder where you've put your .xml file.
Hope it helps

**Comment by MeurglysIII** [comment]
Thanks! That helped.
