### ISSUE TITLE
Can't load  Standalone Hardware Monitor plugin.

### ISSUE THREAD

**Issue by robercy** [Artemis-RGB/Artemis#841]
When loading Standalone Hardware Monitor, a get this error message:

<img width="407" alt="image" src="https://github.com/Artemis-RGB/Artemis/assets/58106902/00e5f71d-4b2a-4e45-b586-fd45066e61e4">

**Comment by diogotr7** [comment]
Weird, ill look into this

**Comment by diogotr7** [comment]
Fixed, update it to v1.0.0.1 please from the workshop.
