### ISSUE TITLE
OpenRGB 

### ISSUE THREAD

**Issue by LorLis84** [Artemis-RGB/Artemis#857]
As soon as I launch the opergb plugin it crashes
I use an ASUS Strix Scope II keyboard and I have altedy deactivate the ASUS service

**Comment by evertonstz** [comment]
I was having the same issue, in my case the problem is that I was using an alpha build of OpenRGB, try downloading the latest stable version (0.9 i believe).

**Comment by LorLis84** [comment]
The thing is that the stable version don't support my keyboard

**Comment by evertonstz** [comment]
> The thing is that the stable version don't support my keyboard

Well, that's some bad luck, I'm on the same boat with my video card. We probably won't be seen this being worked on until openRGB releases a new stable version, and that can take months. If you're savy enough you probably can clone openRGB, switch to their stable tag and patch the pull request that implemented support for your keyboard and try to compile.
